spring.application.name=sumativa2

server.port=8080
aws.region=us-east-1
aws.s3.bucket=sumativa2-bucket
efs.mount.path=/mnt/efs

jwt.secret=clave-super-secreta-para-minimarket-2024
jwt.expiration-seconds=86400

# Configuracion de H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true